name: authentication
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/images/
